package co.com.smartfit.web.entities;

// default package
// Generated 13/09/2017 08:37:26 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CodigoDescuento generated by hbm2java
 */
public class CodigoDescuento implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String codigo;
    private Boolean asignado;
    private Set empresaAfiliadoXCodigoDescuentos = new HashSet(0);
    private EmpresaEmpleador empresaEmpleador;
    private String periodicidad;

    public CodigoDescuento() {
        super();
    }

    public CodigoDescuento(String codigo) {
        this.codigo = codigo;
    }

    public CodigoDescuento(String codigo, Boolean asignado, Set empresaAfiliadoXCodigoDescuentos, EmpresaEmpleador empresaEmpleador) {
        this.codigo = codigo;
        this.asignado = asignado;
        this.empresaAfiliadoXCodigoDescuentos = empresaAfiliadoXCodigoDescuentos;
        this.empresaEmpleador = empresaEmpleador;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Boolean getAsignado() {
        return this.asignado;
    }

    public void setAsignado(Boolean asignado) {
        this.asignado = asignado;
    }

    public String getPeriodicidad() { return periodicidad; }

    public void setPeriodicidad(String periodicidad) { this.periodicidad = periodicidad; }

    public Set getEmpresaAfiliadoXCodigoDescuentos() {
        return this.empresaAfiliadoXCodigoDescuentos;
    }

    public void setEmpresaAfiliadoXCodigoDescuentos(Set empresaAfiliadoXCodigoDescuentos) {
        this.empresaAfiliadoXCodigoDescuentos = empresaAfiliadoXCodigoDescuentos;
    }

	public EmpresaEmpleador getEmpresaEmpleador() {
		return empresaEmpleador;
	}

	public void setEmpresaEmpleador(EmpresaEmpleador empresaEmpleador) {
		this.empresaEmpleador = empresaEmpleador;
	}

    
}
