package co.com.smartfit.web.entities;


import co.com.smartfit.web.dao.EmpresaEmpleadorXPlanDao;

import java.io.Serializable;
/**
 * CodigoDescuento generated by hbm2java
 */
public class CodigoDescuento implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    //Campos en DB
    private Integer id;
    private String codigo;
    private Boolean asignado;
    private Integer idEmpresaPlan;

    //Relaciones
    private EmpresaEmpleadorXPlanDao empresaEmpleadorXPlanDao = new EmpresaEmpleadorXPlanDao();
    private EmpresaEmpleadorXPlan empresaEmpleadorXPlan;

    public CodigoDescuento() {
        super();
    }

    public CodigoDescuento(String codigo, Boolean asignado,
                           Integer idEmpresaPlan) {
        this.codigo = codigo;
        this.asignado = asignado;
        this.idEmpresaPlan = idEmpresaPlan;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Boolean getAsignado() {
        return this.asignado;
    }

    public void setAsignado(Boolean asignado) {
        this.asignado = asignado;
    }

    public Integer getIdEmpresaPlan() {
        return idEmpresaPlan;
    }

    public void setIdEmpresaPlan(Integer idEmpresaPlan) {
        this.idEmpresaPlan = idEmpresaPlan;
    }

    public EmpresaEmpleadorXPlan getEmpresaEmpleadorXPlan() {
        return this.empresaEmpleadorXPlanDao.getEmpresaEmpleadorXPlanById(this.idEmpresaPlan);
    }

    public void setEmpresaEmpleadorXPlan(EmpresaEmpleadorXPlan empresaEmpleadorXPlan) {
        this.empresaEmpleadorXPlan = empresaEmpleadorXPlan;
    }
}