package co.com.smartfit.web.entities;

import java.util.Date;

/**
 * EmpresaAfiliadoXCodigoDescuento generated by hbm2java
 */
public class EmpresaAfiliadoXCodigoDescuento implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private CodigoDescuento codigoDescuento;
    private EmpresaAfiliado empresaAfiliado;
    private Boolean asignado;
    private Date fechaAsignacion;

    public EmpresaAfiliadoXCodigoDescuento() {
        super();
    }

    public EmpresaAfiliadoXCodigoDescuento(CodigoDescuento codigoDescuento, EmpresaAfiliado empresaAfiliado) {
        this.codigoDescuento = codigoDescuento;
        this.empresaAfiliado = empresaAfiliado;
    }

    public EmpresaAfiliadoXCodigoDescuento(CodigoDescuento codigoDescuento, EmpresaAfiliado empresaAfiliado, Boolean asignado,
            Date fechaAsignacion) {
        this.codigoDescuento = codigoDescuento;
        this.empresaAfiliado = empresaAfiliado;
        this.asignado = asignado;
        this.fechaAsignacion = fechaAsignacion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CodigoDescuento getCodigoDescuento() {
        return this.codigoDescuento;
    }

    public void setCodigoDescuento(CodigoDescuento codigoDescuento) {
        this.codigoDescuento = codigoDescuento;
    }

    public EmpresaAfiliado getEmpresaAfiliado() {
        return this.empresaAfiliado;
    }

    public void setEmpresaAfiliado(EmpresaAfiliado empresaAfiliado) {
        this.empresaAfiliado = empresaAfiliado;
    }

    public Boolean getAsignado() {
        return this.asignado;
    }

    public void setAsignado(Boolean asignado) {
        this.asignado = asignado;
    }

    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }

    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }

}
