package co.com.smartfit.web.entities;

// Generated 12-may-2017 13:55:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumentoIdentidad generated by hbm2java
 */
public class Membresia implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set empresaEmpleador = new HashSet(0);

	public Membresia() {
	}

	public Membresia(String nombre) {
		this.nombre = nombre;
	}

	public Membresia(String nombre, Set empresaEmpleador) {
		this.nombre = nombre;
		this.empresaEmpleador = empresaEmpleador;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getEmpresaEmpleador() {
		return this.empresaEmpleador;
	}

	public void setEmpresaEmpleador(Set empresaEmpleador) {
		this.empresaEmpleador = empresaEmpleador;
	}

}
