package co.com.smartfit.web.shipping;

public class HtmlBody {

    public static String getHtmlMembresiaVip(String name, String codigo, String url, String logo, String textoEmail) {
        StringBuffer htmlMessage = new StringBuffer("<!DOCTYPE HTML\">");
        htmlMessage.append("<html>");
        htmlMessage.append("<head>");
        htmlMessage.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
        htmlMessage.append("<title>Correo Informativo</title>");
        htmlMessage.append("</head>");
        htmlMessage.append("<body>");
        htmlMessage.append("<table cellspacing=\"0\" cellpadding=\"0\" width=\"700\" align=\"center\" border=\"0\" style=\"font-family: Arial, Helvetica, sans-serif; font-weight: normal; color: #787b80\">");
        htmlMessage.append("<tbody>");
        htmlMessage.append("<tr>");
        htmlMessage.append("<th colspan=\"2\" scope=\"col\"><img alt=\"Logo\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/upload/image/"+logo+"/\" style=\"max-width: 700px; display: block; margin: auto;\" />");
        htmlMessage.append("</th>");
        htmlMessage.append("</tr>");
        htmlMessage.append("<tr>");
        htmlMessage.append("<th bgcolor=\"#f2f2f3\" colspan=\"2\" scope=\"col\" style=\"padding-bottom: 30px; padding-top: 30px; padding-left: 30px; padding-right: 30px\">");
        htmlMessage.append("<p style=\"font-size: 14px; font-family: Arial, Helvetica, sans-serif; font-weight: normal; color: #787b80; text-align: left; line-height: 22px\">");
        htmlMessage.append("<span style=\"font-size: 24px; color: #ff277e; text-align: left\">");
        htmlMessage.append("<strong>Lleg&oacute; el momento de activarte, ser feliz y saludable</strong>");
        htmlMessage.append("</span>");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("&iexcl;Hola " + name + "!<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Sabemos que tu empresa nos eligi&oacute; como la mejor alternativa para cuidar tu salud, verte y sentirte bien a trav&eacute;s de la actividad f&iacute;sica y el ejercicio bajo la alianza con Smart Fit.");
        htmlMessage.append("<br><br>");
        htmlMessage.append("Sigue los siguientes pasos para activar tu plan:");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Copia este c&oacute;digo " + codigo + " que es la clave de tu beneficio <br>");
        htmlMessage.append("&bull; Ingresa a ");
        htmlMessage.append("<a href= \"" + url + "\">nuestra página</a>");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Sigue los siguientes pasos de inscripción:");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Digita el código promocional y dale click en \"VALIDAR\"");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Selecciona el plan");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Elige una de las sedes, dando click en la imágen");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Por último, diligencia y envía el formulario de datos personales");
        htmlMessage.append("<br><br>");        
        htmlMessage.append("<span style=\"font-size: 16px; color: #787b80; font-weight: bold; text-align: left\">");
        htmlMessage.append("Visualización de pantalla para realización de inscripción:");
        htmlMessage.append("</span>");
        htmlMessage.append("<br><br>");
        htmlMessage.append("<img alt=\"\" style=\"max-width: 700px; display: block; margin: auto;\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/resources/img/VIP_1.PNG\"/>");
        htmlMessage.append("<br>");
        htmlMessage.append("<img alt=\"\" style=\"max-width: 700px; display: block; margin: auto;\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/resources/img/VIP_2.PNG\"/>");
        htmlMessage.append("<br>");
        htmlMessage.append("<span style=\"font-size: 16px; color: #787b80; font-weight: bold; text-align: left\">");
        htmlMessage.append("Recuerda:");
        htmlMessage.append("</span>");
        htmlMessage.append("<br>");
        htmlMessage.append(textoEmail + "<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("El código habilitado posee una vigencia de un trimestre, facturado a la empresa en el mes que se genera.");
        htmlMessage.append("<br>");
        htmlMessage.append("El cobro se realizará independiente de si asistes o no a tu entrenamiento.");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Tu plan se activará en el momento que termines de diligenciar tu proceso de inscripción  No aplica cancelación/traslado de sede/ transferencia de usuario/devoluciones.<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Finaliza tu registro en la recepción de la sede elegida con: registro de huella, registro fotográfico y firma de consentimiento.<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Si eres un usuario activo o antiguo de Smart Fit y deseas activar un código VIP donde la empresa pagará una parte del tu plan, antes de hacer esta activación debes:<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Cancela tu plan antiguo con Smart Fit, en la recepción de la sede donde acudes");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Valida que no tengas pagos pendientes en la recepción");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Si posees Plan Black con cláusula de permanencia de 1 año, paga el 20% del valor correspondiente al periodo restante del tiempo del contrato");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Luego podrás activar tu plan con el código especificado en esta comunicación");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("¡Listo! A partir de este momento ya puedes entrenar.");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Si tienes preguntas sobre tu proceso de inscripción puedes enviar un correo a: ");
        htmlMessage.append("<br>");
        htmlMessage.append("auxilicarcorporativo@smartfit.com.co");
        htmlMessage.append("</p>");
        htmlMessage.append("</th>");
        htmlMessage.append("</tr>");
        htmlMessage.append("<tr>");
        htmlMessage.append("<th style=\"background: #000;\">");
        htmlMessage.append("<img alt=\"\" style=\"margin-top: 10px;\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/resources/img/logoFooter.png\"/>");
        htmlMessage.append("</th>");
        htmlMessage.append("</tr>");
        htmlMessage.append("</tbody>");
        htmlMessage.append("</table>");
        htmlMessage.append("<img src=\"imgabierto.gif\" width=\"10\" height=\"10\">");
        htmlMessage.append("</body>");
        htmlMessage.append("</html>");
        return htmlMessage.toString();
    }

    public static String getHtmlMembresiaConvencional(String name, String codigo, String url, String logo, String textoEmail) {
        StringBuffer htmlMessage = new StringBuffer("<!DOCTYPE HTML\">");
        htmlMessage.append("<html>");
        htmlMessage.append("<head>");
        htmlMessage.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
        htmlMessage.append("<title>Correo Informativo</title>");
        htmlMessage.append("</head>");
        htmlMessage.append("<body>");
        htmlMessage.append("<table cellspacing=\"0\" cellpadding=\"0\" width=\"700\" align=\"center\" border=\"0\" style=\"font-family: Arial, Helvetica, sans-serif; font-weight: normal; color: #787b80\">");
        htmlMessage.append("<tbody>");
        htmlMessage.append("<tr>");
        htmlMessage.append("<th colspan=\"2\" scope=\"col\"><img alt=\"Logo\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/upload/image/"+logo+"/\" style=\"max-width: 700px; display: block; margin: auto;\" />");
        htmlMessage.append("</th>");
        htmlMessage.append("</tr>");
        htmlMessage.append("<tr>");
        htmlMessage.append("<th bgcolor=\"#f2f2f3\" colspan=\"2\" scope=\"col\" style=\"padding-bottom: 30px; padding-top: 30px; padding-left: 30px; padding-right: 30px\">");
        htmlMessage.append("<p style=\"font-size: 14px; font-family: Arial, Helvetica, sans-serif; font-weight: normal; color: #787b80; text-align: left; line-height: 22px\">");
        htmlMessage.append("<span style=\"font-size: 24px; color: #ff277e; text-align: left\">");
        htmlMessage.append("<strong>Lleg&oacute; el momento de activarte, ser feliz y saludable</strong>");
        htmlMessage.append("</span>");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("&iexcl;Hola " + name + "!<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Sabemos que tu empresa nos eligi&oacute; como la mejor alternativa para cuidar tu salud, verte y sentirte bien a trav&eacute;s de la actividad f&iacute;sica y el ejercicio bajo la alianza con Smart Fit.");
        htmlMessage.append("<br><br>");
        htmlMessage.append("Sigue los siguientes pasos para activar tu plan:");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Copia este c&oacute;digo " + codigo + " que es la clave de tu beneficio <br>");
        htmlMessage.append("&bull; Ingresa a ");
        htmlMessage.append("<a href= \"" + url + "\">nuestra página</a>");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Digita Código Promocional");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Selecciona la ciudad en donde quieres entrenar");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Selecciona la sede que mas te convenga");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Dar click en aceptar.");
        htmlMessage.append("<br><br>");        
        htmlMessage.append("<span style=\"font-size: 16px; color: #787b80; font-weight: bold; text-align: left\">");
        htmlMessage.append("Visualización de pantalla para realización de inscripción:");
        htmlMessage.append("</span>");
        htmlMessage.append("<br><br>");
        htmlMessage.append("<img alt=\"\" style=\"max-width: 700px; display: block; margin: auto;\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/resources/img/CONV_1.PNG\"/>");
        htmlMessage.append("<br>");
        htmlMessage.append("<img alt=\"\" style=\"max-width: 700px; display: block; margin: auto;\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/resources/img/CONV_2.PNG\"/>");
        htmlMessage.append("<br>");
        htmlMessage.append("<span style=\"font-size: 16px; color: #787b80; font-weight: bold; text-align: left\">");
        htmlMessage.append("Recuerda:");
        htmlMessage.append("</span>");
        htmlMessage.append("<br>");
        htmlMessage.append(textoEmail + "<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("El código habilitado posee una vigencia de un trimestre, facturado a la empresa en el mes que se genera.");
        htmlMessage.append("<br>");
        htmlMessage.append("El cobro se realizará independiente de si asistes o no a tu entrenamiento.");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Tu plan se activará cuando hayas completado la encuesta médica o cuando hayas asistido a la cita de valoración si el sistema te pide agendarla. ");
        htmlMessage.append("No aplica cancelación/traslado de sede/ transferencia de usuario o devoluciones de dinero.<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Finaliza tu registro en la recepción de la sede elegida con: registro de huella, registro fotográfico y firma de consentimiento.<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Si eres un usuario activo o antiguo de Smart Fit y deseas activar un código donde la empresa pagará una parte del tu plan, antes de hacer esta activación debes:<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Cancela tu plan antiguo con Smart Fit, en la recepción de la sede donde acudes");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Valida que no tengas pagos pendientes en la recepción");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Si posees Plan Black con cláusula de permanencia de 1 año, paga el 20% del valor correspondiente al periodo restante del tiempo del contrato");
        htmlMessage.append("<br>");
        htmlMessage.append("&bull; Luego podrás activar tu plan con el código especificado en esta comunicación");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("¡Listo! A partir de este momento ya puedes entrenar.");
        htmlMessage.append("<br>");
        htmlMessage.append("<br>");
        htmlMessage.append("Si tienes preguntas sobre tu proceso de inscripción puedes enviar un correo a: ");
        htmlMessage.append("<br>");
        htmlMessage.append("auxilicarcorporativo@smartfit.com.co");
        htmlMessage.append("</p>");
        htmlMessage.append("</th>");
        htmlMessage.append("</tr>");
        htmlMessage.append("<tr>");
        htmlMessage.append("<th style=\"background: #000;\">");
        htmlMessage.append("<img alt=\"\" style=\"margin-top: 10px;\" src=\"https://corporativo.smartfitcolombia.com:8081/Admin/resources/img/logoFooter.png\"/>");
        htmlMessage.append("</th>");
        htmlMessage.append("</tr>");
        htmlMessage.append("</tbody>");
        htmlMessage.append("</table>");
        htmlMessage.append("<img src=\"imgabierto.gif\" width=\"10\" height=\"10\">");
        htmlMessage.append("</body>");
        htmlMessage.append("</html>");
        return htmlMessage.toString();
    }
}
