package com.corporativos_smartfit.entities;

import com.corporativos_smartfit.dao.MembresiaDao;
import com.corporativos_smartfit.dao.TipoDocumentoIdentidadDao;
import com.corporativos_smartfit.dto.ErrorGeneral;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpresaEmpleador generated by hbm2java
 */
public class EmpresaEmpleador implements java.io.Serializable {

	private Integer id;
	private String razonSocial;
	private Integer documentoTipo;
	private String documentoNumero;
	private String telefono;
	private String email;
	private boolean activa;
	private String representanteNombre;
	private Date fechaCreacion;
	private Integer idMembresia;
	private String logo;
	private String textoEmail;

	private MembresiaDao membresiaDao = new MembresiaDao();
	private TipoDocumentoIdentidadDao tipoDocumentoIdentidadDao = new TipoDocumentoIdentidadDao();


	private Membresia membresia;
	private TipoDocumentoIdentidad tipoDocumentoIdentidad;
	/*private TipoDocumentoIdentidad tipoDocumentoIdentidad;
	private Set empresaAfiliados = new HashSet(0);
	private Set codigoDescuento = new HashSet(0);
	private Set empresaEmpleadorXPlan = new HashSet(0);
	*/
	public EmpresaEmpleador() {
		super();
	}

	public EmpresaEmpleador(Membresia membresia, TipoDocumentoIdentidad tipoDocumentoIdentidad,
			String razonSocial, String documentoNumero, String telefono, String email, boolean activa,
			Date fechaCreacion, String logo, String textoEmail,Integer documentoTipo,Integer idMembresia) {
		this.razonSocial = razonSocial;
		this.documentoNumero = documentoNumero;
		this.telefono = telefono;
		this.email = email;
		this.activa = activa;
		this.fechaCreacion = fechaCreacion;
		this.logo = logo;
		this.textoEmail = textoEmail;
		this.documentoTipo = documentoTipo;
		this.idMembresia = idMembresia;
		this.membresia = membresia;
		this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
	}

	public EmpresaEmpleador(Membresia membresia,
			String razonSocial, String documentoNumero, String telefono, String email, boolean activa,
			String representanteNombre, Date fechaCreacion, String logo, String textoEmail
			) {
		this.membresia = membresia;
		this.razonSocial = razonSocial;
		this.documentoNumero = documentoNumero;
		this.telefono = telefono;
		this.email = email;
		this.activa = activa;
		this.representanteNombre = representanteNombre;
		this.fechaCreacion = fechaCreacion;
		this.logo = logo;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRazonSocial() {
		return razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public Integer getDocumentoTipo() {
		return documentoTipo;
	}

	public void setDocumentoTipo(Integer documentoTipo) {
		this.documentoTipo = documentoTipo;
	}

	public String getDocumentoNumero() {
		return documentoNumero;
	}

	public void setDocumentoNumero(String documentoNumero) {
		this.documentoNumero = documentoNumero;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isActiva() {
		return activa;
	}

	public void setActiva(boolean activa) {
		this.activa = activa;
	}

	public String getRepresentanteNombre() {
		return representanteNombre;
	}

	public void setRepresentanteNombre(String representanteNombre) {
		this.representanteNombre = representanteNombre;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Integer getIdMembresia() {
		return idMembresia;
	}

	public void setIdMembresia(Integer idMembresia) {
		this.idMembresia = idMembresia;
	}

	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getTextoEmail() {
		return textoEmail;
	}

	public void setTextoEmail(String textoEmail) {
		this.textoEmail = textoEmail;
	}

	public Membresia getMembresia() {
		if (this.membresia == null) {
			this.membresia= this.membresiaDao.getMembresiaPorId(this.idMembresia);
		}
		return this.membresia;
	}

	public void setMembresia(Membresia membresia) {
		this.membresia = membresia;
	}

	public TipoDocumentoIdentidad getTipoDocumentoIdentidad() throws ErrorGeneral {
		if (this.tipoDocumentoIdentidad == null) {
			this.tipoDocumentoIdentidad= this.tipoDocumentoIdentidadDao.obtenerTipoDocumentoPorId(this.documentoTipo);
		}
		return this.tipoDocumentoIdentidad;
	}

	public void setTipoDocumentoIdentidad(TipoDocumentoIdentidad tipoDocumentoIdentidad) {
		this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
	}


}
